### ISSUE TITLE
Notify url not working in sandbox environment

### ISSUE THREAD

**Issue by kik-doctor** [ingameltd/payu#1]
Hello, I have following 2 issues.
1. After creating order, I get these error from PayU.captureOrder().
error from payu PayUError: statusCode = ERROR_VALUE_INVALID, code = 108, codeLiteral = ERROR_VALUE_INVALID, statusDesc = Order has incorrect status. Transition is impossible.
    at PayU.<anonymous> (E:\Web\work\Progress\0007-medical-mean\MEVICO\Server\node_modules\@ingameltd\payu\dist\PayU.js:114:23)
    at Generator.throw (<anonymous>)
    at rejected (E:\Web\work\Progress\0007-medical-mean\MEVICO\Server\node_modules\@ingameltd\payu\dist\PayU.js:6:65)
    at tryCatcher (E:\Web\work\Progress\0007-medical-mean\MEVICO\Server\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Web\work\Progress\0007-medical-mean\MEVICO\Server\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\Web\work\Progress\0007-medical-mean\MEVICO\Server\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\Web\work\Progress\0007-medical-mean\MEVICO\Server\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\Web\work\Progress\0007-medical-mean\MEVICO\Server\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (E:\Web\work\Progress\0007-medical-mean\MEVICO\Server\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\Web\work\Progress\0007-medical-mean\MEVICO\Server\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\Web\work\Progress\0007-medical-mean\MEVICO\Server\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Web\work\Progress\0007-medical-mean\MEVICO\Server\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)

2. How  can I get response from notify url in node.js backend ?
Thanks in advance.

**Comment by kasvith** [comment]
can you show me what was your notifyUrl ?

**Comment by kasvith** [comment]
1. It seems your order status is invalid. To capture order you must disable automatic payout collection in your PayU store. It's listed on PayU developer guide. 

Usually, PayU has enabled automatic payout collection, thus after payment your order is already collected by PayU. Hence you cant(or don't need to capture the payment and manually approve it).

2. If you using localhost, you may want to forward traffic from PayU to your local machine using something like Ngrok. Then replace localhost in notify URL with the address given by ngrok. 

To get the order notification, payU expect you to handle a POST request sent to the NotifyUrl given by you.

Please note that this is not a problem with the library, for more please refer PayU developer docs. 

Thanks for using the lib 😃

**Comment by kik-doctor** [comment]
Thanks for your quick response.
Let me try with your advice.
Regards, Topwolf.

**Comment by kasvith** [comment]
thanks for using the library :) if you find this library useful feel free to add a star ⭐

**Comment by kasvith** [comment]
glad to help

**Comment by kik-doctor** [comment]
Hello, dear Kasun
I would like you to help me one more time.
I am trying to get responses from notifyUrl using ngrok.
I think that ngrok can not handle POST request and can handle only GET
request.
There is any error, but I can not get any info from notifyUrl.
Thanks,

**Comment by kik-doctor** [comment]
I have done completely.
Thanks for your help.
Let's rate this repository !!!

**Comment by kasvith** [comment]
a pleasure to help ☺️
